server:
  port: 8888

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: boot.spring.po

spring:
  datasource:
    url: jdbc:mysql://192.168.2.209:3306/activiti
    driver-class-name: com.mysql.jdbc.Driver
    username: opsa
    password: pass123456
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full
  thymeleaf:
    mode: LEGACYHTML5

logging:
  config: classpath:log4j2.xml
  


